# Generated by Django 6.0.4 on 2026-04-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
    ]
